input_dir: /lus/eagle/projects/FoundEpidem/braceal/projects/kbase-protein-search/data/sprot
output_dir: examples/sprot/sprot_esm_8m_embeddings
glob_patterns: ['*.fasta']
num_data_workers: 4
batch_size: 128

embedder_config:
  name: esm2
  pretrained_model_name_or_path: facebook/esm2_t6_8M_UR50D

compute_config:
  name: polaris
  num_nodes: 2
  worker_init: "module load conda/2023-10-04; conda activate protein-search; export HF_HOME=/lus/eagle/projects/CVD-Mol-AI/braceal/.cache/"
  scheduler_options: "#PBS -l filesystems=home:eagle:grand"
  account: FoundEpidem
  queue: debug-scaling
  walltime: 01:00:00
